cc_library(
    name = "stack_trace",
    srcs = ["stacktrace.hpp"],
    linkopts = ["-ldl"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "test",
    srcs = ["test.cpp"],
    hdrs = ["test.hpp"],
    visibility = ["//visibility:public"],
)
